### ISSUE TITLE
sbt.TestsFailedException: Tests unsuccessful. Error during tests: TestParallelContrast

### ISSUE THREAD

**Issue by alanmazankiewicz** [edouardfouche/MCDE#1]
When running sbt test it only complained about TestParallelContrast (see attachment). However, when running the examples in Parallel (-p 1 or -p 3, for both `EstimateDependency` and `EstimateDependencyMatrix`) it does say that it executes in parallel. 

[[MacBook-Pro-4:MCDE Mazan$ sbt test.txt](https://github.com/edouardfouche/MCDE/files/2437233/MacBook-Pro-4.MCDE.Mazan.sbt.test.txt)

**Comment by edouardfouche** [comment]
It seems that this is a machine-dependent problem. We will remove the tests that use p > 1 to avoid such misleading failures in the next commit. Thank you.
