### ISSUE TITLE
Running EstimateDependency without specifying -d command crashes 

### ISSUE THREAD

**Issue by alanmazankiewicz** [edouardfouche/MCDE#2]
According to Readme -d should have a default behaviour. However, when not specifying a java.lang.ArrayIndexOutOfBoundsException: 110 is thrown (See Attachment)

[Error when not specifing dimensions.txt](https://github.com/edouardfouche/MCDE/files/2437250/Error.when.not.specifing.dimensions.txt)

**Comment by edouardfouche** [comment]
Thx for the feedback. The bug was found in the Main class. Closing as it will be corrected in the next commit.
