### ISSUE TITLE
Statistical test CMI could not be found 

### ISSUE THREAD

**Issue by alanmazankiewicz** [edouardfouche/MCDE#3]
When running the application with the `-a  CMI` approach an java.lang.Error: Unknown statistical test CMI is thrown (see attachment). This behaviour can be observed using both `-t EstimateDependecy`and `-t EstimateDependecyMatrix` as well as with the forzen .jar file and `sbt "run <arguments>"`. 

[Unknown Statistical Test.txt](https://github.com/edouardfouche/MCDE/files/2437280/Unknown.Statistical.Test.txt)

**Comment by edouardfouche** [comment]
Thx for the feedback. The bug was found in StatsFactory. Closing as it will be corrected in the next commit.
